import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from uda_hub.agentic.tools.tools import RESEARCHER_TOOLS
from uda_hub.agentic.tools.udahub_state import UDAHubState

from langchain.agents import create_agent

load_dotenv()


# ==========================================
# 2. CUSTOM create_agent FACTORY
# ==========================================
def create_agent_wrapper(
    name: str,
    model,
    tools: list,
    system_prompt: str,
    checkpointer=None,
    interrupt_before: list[str] | None = None,
):
    """
    Returns a compiled LangGraph ReAct agent.
    """
    # FIXED: Using create_react_agent
    return create_agent(
        model=model,
        tools=tools,
        system_prompt=system_prompt,  # LangGraph uses state_modifier for the prompt
        checkpointer=checkpointer,
        interrupt_before=interrupt_before,
        name=name,
    )


# ==========================================
# 3. AGENT INSTANCE
# ==========================================
llm = ChatOpenAI(
    model="gpt-4o",
    temperature=0.0,
    base_url="https://openai.vocareum.com/v1",
    api_key=os.getenv("VOCAREUM_API_KEY"),
)

researcher_agent = create_agent_wrapper(
    name="researcher_agent",
    model=llm,
    tools=RESEARCHER_TOOLS,
    system_prompt=(
        "You are the UDA-Hub Researcher Agent. Your mission is to find factual truth using provided tools.\n"
        "1. Focus strictly on the 'Anchored Ticket' provided in the input.\n"
        "2. Query 'udahub.db' for policies in the knowledge table (title, content).\n"
        "3. Query 'cultpass.db' to verify user reservations (join reservations and experiences tables).\n"
        "4. DO NOT reply to the customer. Output a bulleted list of facts found.\n"
        "5. If a user_id is provided, verify their tier and booking status[cite: 582]."
    ),
)


def researcher_node(state: UDAHubState):
    """
    Orchestrates the Researcher Agent. It passes the Anchor (ticket_text)
    and User Context (user_id/tier) to the agent.
    """
    # Use the Anchored ticket_text, not the raw chat history
    anchor = state.get("ticket_text")
    user_id = state.get("user_id")
    tier = state.get("customer_tier", "regular")

    # Construction of the agent's task
    prompt_task = (
        f"ANCHORED TICKET: {anchor}\n"
        f"USER CONTEXT: ID={user_id}, Tier={tier}\n\n"
        "Please find the relevant policies and verify any associated bookings."
    )

    # We use the existing thread_id for consistency across the sub-agent call
    config = {
        "configurable": {"thread_id": state.get("user_id", "internal_research_turn")}
    }

    # Execute the agent
    # Note: We pass the task as a human message to the ReAct agent
    result = researcher_agent.invoke({"messages": [("user", prompt_task)]}, config)

    # Return the findings to the 'research_facts' key in the UDAHubState
    return {"research_facts": result["messages"][-1].content}


# ==========================================
# 4. TEST SCRIPT
# ==========================================
# Place this at the bottom of your researcher.py file

if __name__ == "__main__":
    print("--- RUNNING SUCCESSFUL RESEARCHER TEST ---")

    # 1. Mocking the exact state as it would come from the Enricher & Classifier
    # We use Alice's exact ID so the SQL tools will find real data.
    successful_state: UDAHubState = {
        "ticket_text": "I have a reservation for the Christ the Redeemer Experience but I can't go anymore. What is your refund policy for events?",
        "user_email": "alice.kingsley@wonderland.com",
        "user_id": "a4ab87",  # Alice's real ID in cultpass.db
        "customer_tier": "basic",  # Alice's real tier
        "subscription_status": "cancelled",  # Alice's real status
        "category": "billing",
        "urgency": "standard",
        "research_facts": None,
    }

    print(f"\nUser: {successful_state['user_email']}")
    print(f"Ticket: '{successful_state['ticket_text']}'\n")
    print("Agent is thinking and querying tools... (Look for the tool logs below)\n")
    print("-" * 50)

    # 2. Call the node directly
    result = researcher_node(successful_state)

    # 3. Print the final proper response
    print("-" * 50)
    print("\n✅ FINAL RESEARCH FACTS GENERATED BY AGENT:\n")
    print(result["research_facts"])
