import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from uda_hub.agentic.tools.tools import RESEARCHER_TOOLS
from uda_hub.agentic.tools.udahub_state import UDAHubState

from langchain.agents import create_agent

load_dotenv()


# ==========================================
# 2. CUSTOM create_agent FACTORY
# ==========================================
def create_agent_wrapper(
    name: str,
    model,
    tools: list,
    system_prompt: str,
    checkpointer=None,
    interrupt_before: list[str] | None = None,
):
    """
    Returns a compiled LangGraph ReAct agent.
    """
    # FIXED: Using create_react_agent
    return create_agent(
        model=model,
        tools=tools,
        system_prompt=system_prompt,  # LangGraph uses state_modifier for the prompt
        checkpointer=checkpointer,
        interrupt_before=interrupt_before,
        name=name,
    )


# ==========================================
# 3. AGENT INSTANCE
# ==========================================
llm = ChatOpenAI(
    model="gpt-4o",
    temperature=0.0,
    base_url="https://openai.vocareum.com/v1",
    api_key=os.getenv("VOCAREUM_API_KEY"),
)

researcher_agent = create_agent_wrapper(
    name="researcher_agent",
    model=llm,
    tools=RESEARCHER_TOOLS,
    system_prompt=(
        "You are the UDA-Hub Researcher Agent. Your job is to find factual truth.\n"
        "1. Use tools to query the provided databases.\n"
        "2. DO NOT write a response to the customer.\n"
        "3. Output ONLY a bulleted list of facts found (e.g., booking status, refund policy).\n"
        "If information is missing after tool usage, state what is missing."
    ),
)


def researcher_node(state: UDAHubState):
    config = {"configurable": {"thread_id": state.get("user_id", "default_thread")}}

    # Run the agent (must pass the messages array explicitly for create_react_agent)
    # The agent expects a list of messages as input, so we convert the ticket text into a human message
    result = researcher_agent.invoke(
        {
            "messages": [
                (
                    "user",
                    f"Ticket: {state.get('ticket_text')}\nUser ID: {state.get('user_id')}",
                )
            ]
        },
        config,
    )

    # Grab the last message from the agent's internal list
    return {"research_facts": result["messages"][-1].content}


# ==========================================
# 4. TEST SCRIPT
# ==========================================
# Place this at the bottom of your researcher.py file

if __name__ == "__main__":
    print("--- RUNNING SUCCESSFUL RESEARCHER TEST ---")

    # 1. Mocking the exact state as it would come from the Enricher & Classifier
    # We use Alice's exact ID so the SQL tools will find real data.
    successful_state: UDAHubState = {
        "ticket_text": "I have a reservation for the Christ the Redeemer Experience but I can't go anymore. What is your refund policy for events?",
        "user_email": "alice.kingsley@wonderland.com",
        "user_id": "a4ab87",  # Alice's real ID in cultpass.db
        "customer_tier": "basic",  # Alice's real tier
        "subscription_status": "cancelled",  # Alice's real status
        "category": "billing",
        "urgency": "standard",
        "research_facts": None,
    }

    print(f"\nUser: {successful_state['user_email']}")
    print(f"Ticket: '{successful_state['ticket_text']}'\n")
    print("Agent is thinking and querying tools... (Look for the tool logs below)\n")
    print("-" * 50)

    # 2. Call the node directly
    result = researcher_node(successful_state)

    # 3. Print the final proper response
    print("-" * 50)
    print("\n✅ FINAL RESEARCH FACTS GENERATED BY AGENT:\n")
    print(result["research_facts"])
